variables:
  NAME: "aeca"
  MAJOR: "1"
  MINOR: "0.0"
  BUILD: $BUILD_VERSION

stages:
  - versioning
  - building
  - testing      
  - packaging 
  - db_update
  - deployment
  - custom

before_script:
  - echo "$GITLAB_USER_LOGIN! runs build for $CI_BUILDS_DIR"    
  - echo "$CI_COMMIT_AUTHOR pushed to $CI_COMMIT_BRANCH with message $CI_COMMIT_DESCRIPTION"
  - chmod -R +x ./build/ci_scripts/

versioning-job:
  stage:
    versioning
  tags:
    - Any
  only:  
    - develop
    - master    
  script:
    - BUILD=$((BUILD_VERSION + 1))
    - ./build/ci_scripts//version_set.sh
    - echo "$BUILD"
  when: manual
  allow_failure: true
  resource_group: production

npm-build-job:
  stage: 
    building
  tags:
    - RedOS73 
  script:  
    - ./build/ci_scripts//build_npm.sh
  when: manual
  artifacts:
    paths:    
    - artifacts/*.zip
    expire_in: 3 days
  allow_failure: true

mvn-build-job:
  stage: 
    building
  tags:
    - AstraLinux  
  script:  
    - ./build/ci_scripts//build_mvn.sh
  when: manual
  artifacts:
    paths:    
    - src/aeca-EEE/target/*.zip
    expire_in: 3 days
  allow_failure: true

cmake-build-job:
  stage: 
    building
  tags:
    - RedOS73 
  script:  
    - ./build/ci_scripts//build_cmake.sh
  when: manual
  artifacts:
    paths:    
    - src/aeca-COE/src/main/opensslfasad/*.zip
    expire_in: 3 days
  allow_failure: true

test-job:  
  stage: 
    testing
  tags:
    - Any
  script:     
     - ./build/ci_scripts//test.sh
  when: manual
  allow_failure: true

rpmbuild-job:
  stage: 
    packaging
  tags:
    - RedOS73
  only:    
    - develop
    - master   
    - experimental
  script:      
    - ./build/ci_scripts//createrpm.sh
  when: manual
  artifacts:
    paths:    
    - artifacts/*.rpm
    expire_in: 3 days
  resource_group: production

deb_build-job:
  stage:
    packaging
  tags:
    - AstraLinux17
  only:
    - develop
    - master
    - feature/78215
  script:
    - ./build/ci_scripts//createdeb.sh
  when: manual
  artifacts:
    when: on_success
    paths:    
    - artifacts1/*.deb
    expire_in: 3 days
  resource_group: production

deployment-redos:  
  stage: 
    deployment
  only:    
    - develop
    - master  
  tags:
    - RedOS73
  script:
    - ./build/ci_scripts//deploy.sh
  when: manual
  allow_failure: true
  resource_group: production

deployment-astra:  
  stage: 
    deployment
  only:    
    - develop
    - master  
  tags:
    - AstraLinux17
  script:
    - ./build/ci_scripts//deploy.sh
  when: manual
  allow_failure: true
  resource_group: production

update-db-job-maria-redos:  
  stage: 
    db_update
  only:    
    - develop
    - master
  tags:
    - RedOS73
  script:
    - ./build/ci_scripts//updatedb_maria.sh
  when: manual
  allow_failure: true
  resource_group: production

update-db-job-postgres-astra:  
  stage: 
    db_update
  only:    
    - develop
    - master
  tags:
    - AstraLinux17
  script:
    - ./build/ci_scripts//updatedb_postgres.sh
  when: manual
  allow_failure: true
  resource_group: production
