/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libJniTest */

#ifndef _Included_libJniTest
#define _Included_libJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libJniTest
 * Method:    showString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_libJniTest_showString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
