/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLFasadTest */

#ifndef _Included_OpenSSLFasadTest
#define _Included_OpenSSLFasadTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLFasadTest
 * Method:    CreateSert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_OpenSSLFasadTest_CreateSert
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
